services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        PYTHON_VERSION: 3.9
        POETRY_VERSION: 1.5.1
    image: py-init:v0.0.1
    container_name: py-init
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./app # Watch for changes in your app directory
          target: /app # Sync changes to the container's /app directory
          ignore:
            - node_modules/ # Ignore the node_modules directory
        - action: rebuild
          path: ./app/requirements.txt # Rebuild if requirements change
    volumes:
      - ./src/config/settings.toml:/app/config/settings.toml
